[package]
name = "kucoin"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
reqwest = "0.8"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
time = "0.1.38"
ring = "0.13.0-alpha"
hex = "0.3"
